name: Atlas Migrate Lint
on:
  pull_request:
    paths:
      - 'migrations/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          dir: 'file://migrations'
          dir-name: 'test-repo'
          dev-url: 'docker://postgres/16/dev?search_path=public'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
